
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBydWViYSIsImlkIjoiNjgxNjQwZTQ4MGRhYWQ0MGQ5MDU1Y2MxIiwiaWF0IjoxNzQ2MzAxMzI4fQ.sjm666UrD3UDtjYQeSeQT-qhFydISYsBRCwR3VVr7jo

{
    "title": "prueba de DELETE",
    "author": "prueba de DELETE",
    "url": "https://delete.com",
    "likes": 2
}

